export const metadata = {
    title: "Cart | Avantgarde",
    description: "Generated by create next app",
};

export default function Page({ params }) {
    return (
        <main className="px-4 pb-4 font-medium">
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-semibold">Cart</h1>
        </main>
    )
}