import ReactMarkdown from "react-markdown";

import { getData } from "../utilities/getData";
import ProductsInCart from "@/components/ProductsInCart/ProductsInCart";

export const metadata = {
    title: "Cart | Avantgarde",
    description: "Generated by create next app",
};

export default async function Page({ params }) {
    const data = await getData('http://localhost:1337/api/cart-shipping-page');

    return (
        <main className="font-medium w-full">
            <h1 className="sr-only">Cart</h1>
            <div className="flex flex-col gap-4 md:flex-row justify-end">
                <ReactMarkdown className="max-w-96 px-4 md:pr-0">
                    {data.data.attributes['cartShippingText']}
                </ReactMarkdown>
                <ProductsInCart/>
            </div>
        </main>
    )
}