export const metadata = {
    title: "Cancelled Order | Avantgarde",
    description: "Generated by create next app",
};

export default async function Page() {
    return (
        <main className="px-4 pb-4 max-w-5xl ml-auto">
            <h1>Cancelled order.</h1>
        </main>
    )
}