import { redirect } from 'next/navigation';
import stripe from 'stripe';

export const metadata = {
    title: "Cancelled Order | Avantgarde",
    description: "Generated by create next app",
};

export default async function Page({ searchParams }) {
  const sessionId = searchParams.session_id;

  if (!sessionId) {
    redirect('/');
  }

  const stripeInstance = stripe(process.env.STRIPE_SECRET_KEY);

  try {
    const session = await stripeInstance.checkout.sessions.retrieve(sessionId);

    if (!session || session.payment_status === 'paid') {
      redirect('/');
    }

    return (
        <main className="px-4 pb-4 max-w-5xl mx-auto">
            <h1>Cancelled order.</h1>
        </main>
    );
  } catch (error) {
    redirect('/');
  }
}