import ReactMarkdown from "react-markdown";

import { getData } from "../utilities/getData";

export const metadata = {
    title: "Contact | Avantgarde",
    description: "Generated by create next app",
};

export default async function Page() {
    const data = await getData('http://localhost:1337/api/contact-page');

    return (
        <main className="px-4 pb-4 max-w-4xl ml-auto">
            <h1 className="sr-only">Contact</h1>
            <ReactMarkdown className="information-rich-text">
                {data.data.attributes['ContactContent']}
            </ReactMarkdown>
        </main>
    )
}