export const metadata = {
    title: "Successful Order | Avantgarde",
    description: "Generated by create next app",
};

export default async function Page() {
    return (
        <main className="px-4 pb-4 max-w-5xl mx-auto">
            <h1>Successful order.</h1>
        </main>
    )
}