import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import LenisLayout from "@/components/LenisLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avantgarde",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} uppercase flex flex-col min-h-screen bg-slate-200`}>
        <Header/>
          <LenisLayout>
            {children}
          </LenisLayout>
      </body>
    </html>
  );
}
