import { Inter } from "next/font/google";
import "./globals.css";
import "./tailwind.css";
import Header from "@/components/Header/Header";
import LenisLayout from "@/components/LenisLayout/LenisLayout";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avantgarde",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen bg-slate-100 text-black/85 font-medium`}>
          <LenisLayout>
            <Providers>
              <Header/>
              {children}
            </Providers>
          </LenisLayout>
      </body>
    </html>
  );
}
