import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import LenisLayout from "@/components/LenisLayout";
import Template from "./template";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} uppercase flex flex-col min-h-screen`}>
        <Header/>
        <Template>
          <LenisLayout>
            {children}
          </LenisLayout>
        </Template>
      </body>
    </html>
  );
}
